name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} • ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
        build_type: [Release]

    env:
      QT_VERSION: '6.9.1'
      BUILD_DIR: build
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.18

      # -------- Linux deps --------
      - name: Install Ninja (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      # -------- macOS deps --------
      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      # -------- Windows deps --------
      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        run: choco install ninja -y

      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Qt ${{ env.QT_VERSION }}
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          cache: true
          install-deps: true
          modules: 'qtserialport'
          arch: ${{ runner.os == 'Windows' && 'win64_msvc2022_64' || '' }}

      - name: Configure
        run: >
          cmake -S . -B ${{ env.BUILD_DIR }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          ${{ runner.os == 'Windows' && '-DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl' || '' }}
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_PREFIX_PATH="${{ env.QT_ROOT_DIR }}"

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.build_type }} --parallel

      # Optional: run tests
      - name: Test
        run: ctest --test-dir ${{ env.BUILD_DIR }} --build-config ${{ matrix.build_type }} --output-on-failure
